/*
 * generated by Xtext 2.14.0
 */
package ck2xtext.common.ide;

import ck2xtext.common.Ck2TerminalsRuntimeModule;
import ck2xtext.common.Ck2TerminalsStandaloneSetup;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class Ck2TerminalsIdeSetup extends Ck2TerminalsStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new Ck2TerminalsRuntimeModule(), new Ck2TerminalsIdeModule()));
	}
	
}
