/*
 * generated by Xtext 2.15.0
 */
package ck2xtext.gfx.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractCk2GfxValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(ck2xtext.gfx.ck2gfx.Ck2gfxPackage.eINSTANCE);
		return result;
	}
}
