/**
 * generated by Xtext 2.15.0
 */
package ck2xtext.gfx.ck2gfx;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Animated Sprite Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ck2xtext.gfx.ck2gfx.AnimatedSpriteType#getName <em>Name</em>}</li>
 *   <li>{@link ck2xtext.gfx.ck2gfx.AnimatedSpriteType#getTexturefile <em>Texturefile</em>}</li>
 *   <li>{@link ck2xtext.gfx.ck2gfx.AnimatedSpriteType#getNoOfFrames <em>No Of Frames</em>}</li>
 *   <li>{@link ck2xtext.gfx.ck2gfx.AnimatedSpriteType#getAnimationRateFps <em>Animation Rate Fps</em>}</li>
 *   <li>{@link ck2xtext.gfx.ck2gfx.AnimatedSpriteType#isLooping <em>Looping</em>}</li>
 *   <li>{@link ck2xtext.gfx.ck2gfx.AnimatedSpriteType#isPlayOnShow <em>Play On Show</em>}</li>
 * </ul>
 *
 * @see ck2xtext.gfx.ck2gfx.Ck2gfxPackage#getAnimatedSpriteType()
 * @model
 * @generated
 */
public interface AnimatedSpriteType extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see ck2xtext.gfx.ck2gfx.Ck2gfxPackage#getAnimatedSpriteType_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link ck2xtext.gfx.ck2gfx.AnimatedSpriteType#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Texturefile</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Texturefile</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Texturefile</em>' attribute.
   * @see #setTexturefile(String)
   * @see ck2xtext.gfx.ck2gfx.Ck2gfxPackage#getAnimatedSpriteType_Texturefile()
   * @model
   * @generated
   */
  String getTexturefile();

  /**
   * Sets the value of the '{@link ck2xtext.gfx.ck2gfx.AnimatedSpriteType#getTexturefile <em>Texturefile</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Texturefile</em>' attribute.
   * @see #getTexturefile()
   * @generated
   */
  void setTexturefile(String value);

  /**
   * Returns the value of the '<em><b>No Of Frames</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>No Of Frames</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>No Of Frames</em>' attribute.
   * @see #setNoOfFrames(int)
   * @see ck2xtext.gfx.ck2gfx.Ck2gfxPackage#getAnimatedSpriteType_NoOfFrames()
   * @model
   * @generated
   */
  int getNoOfFrames();

  /**
   * Sets the value of the '{@link ck2xtext.gfx.ck2gfx.AnimatedSpriteType#getNoOfFrames <em>No Of Frames</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>No Of Frames</em>' attribute.
   * @see #getNoOfFrames()
   * @generated
   */
  void setNoOfFrames(int value);

  /**
   * Returns the value of the '<em><b>Animation Rate Fps</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Animation Rate Fps</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Animation Rate Fps</em>' attribute.
   * @see #setAnimationRateFps(double)
   * @see ck2xtext.gfx.ck2gfx.Ck2gfxPackage#getAnimatedSpriteType_AnimationRateFps()
   * @model
   * @generated
   */
  double getAnimationRateFps();

  /**
   * Sets the value of the '{@link ck2xtext.gfx.ck2gfx.AnimatedSpriteType#getAnimationRateFps <em>Animation Rate Fps</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Animation Rate Fps</em>' attribute.
   * @see #getAnimationRateFps()
   * @generated
   */
  void setAnimationRateFps(double value);

  /**
   * Returns the value of the '<em><b>Looping</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Looping</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Looping</em>' attribute.
   * @see #setLooping(boolean)
   * @see ck2xtext.gfx.ck2gfx.Ck2gfxPackage#getAnimatedSpriteType_Looping()
   * @model
   * @generated
   */
  boolean isLooping();

  /**
   * Sets the value of the '{@link ck2xtext.gfx.ck2gfx.AnimatedSpriteType#isLooping <em>Looping</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Looping</em>' attribute.
   * @see #isLooping()
   * @generated
   */
  void setLooping(boolean value);

  /**
   * Returns the value of the '<em><b>Play On Show</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Play On Show</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Play On Show</em>' attribute.
   * @see #setPlayOnShow(boolean)
   * @see ck2xtext.gfx.ck2gfx.Ck2gfxPackage#getAnimatedSpriteType_PlayOnShow()
   * @model
   * @generated
   */
  boolean isPlayOnShow();

  /**
   * Sets the value of the '{@link ck2xtext.gfx.ck2gfx.AnimatedSpriteType#isPlayOnShow <em>Play On Show</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Play On Show</em>' attribute.
   * @see #isPlayOnShow()
   * @generated
   */
  void setPlayOnShow(boolean value);

} // AnimatedSpriteType
