/**
 * generated by Xtext 2.15.0
 */
package ck2xtext.gfx.ck2gfx;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Arrow Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ck2xtext.gfx.ck2gfx.ArrowType#getName <em>Name</em>}</li>
 *   <li>{@link ck2xtext.gfx.ck2gfx.ArrowType#getSize <em>Size</em>}</li>
 *   <li>{@link ck2xtext.gfx.ck2gfx.ArrowType#getTextureFile <em>Texture File</em>}</li>
 *   <li>{@link ck2xtext.gfx.ck2gfx.ArrowType#getBodyTexture <em>Body Texture</em>}</li>
 *   <li>{@link ck2xtext.gfx.ck2gfx.ArrowType#getColor <em>Color</em>}</li>
 *   <li>{@link ck2xtext.gfx.ck2gfx.ArrowType#getColor2 <em>Color2</em>}</li>
 *   <li>{@link ck2xtext.gfx.ck2gfx.ArrowType#getEndAt <em>End At</em>}</li>
 *   <li>{@link ck2xtext.gfx.ck2gfx.ArrowType#getHeight <em>Height</em>}</li>
 *   <li>{@link ck2xtext.gfx.ck2gfx.ArrowType#getType <em>Type</em>}</li>
 *   <li>{@link ck2xtext.gfx.ck2gfx.ArrowType#getHeading <em>Heading</em>}</li>
 *   <li>{@link ck2xtext.gfx.ck2gfx.ArrowType#getEffect <em>Effect</em>}</li>
 * </ul>
 *
 * @see ck2xtext.gfx.ck2gfx.Ck2gfxPackage#getArrowType()
 * @model
 * @generated
 */
public interface ArrowType extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see ck2xtext.gfx.ck2gfx.Ck2gfxPackage#getArrowType_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link ck2xtext.gfx.ck2gfx.ArrowType#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Size</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Size</em>' attribute.
   * @see #setSize(double)
   * @see ck2xtext.gfx.ck2gfx.Ck2gfxPackage#getArrowType_Size()
   * @model
   * @generated
   */
  double getSize();

  /**
   * Sets the value of the '{@link ck2xtext.gfx.ck2gfx.ArrowType#getSize <em>Size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Size</em>' attribute.
   * @see #getSize()
   * @generated
   */
  void setSize(double value);

  /**
   * Returns the value of the '<em><b>Texture File</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Texture File</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Texture File</em>' attribute.
   * @see #setTextureFile(String)
   * @see ck2xtext.gfx.ck2gfx.Ck2gfxPackage#getArrowType_TextureFile()
   * @model
   * @generated
   */
  String getTextureFile();

  /**
   * Sets the value of the '{@link ck2xtext.gfx.ck2gfx.ArrowType#getTextureFile <em>Texture File</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Texture File</em>' attribute.
   * @see #getTextureFile()
   * @generated
   */
  void setTextureFile(String value);

  /**
   * Returns the value of the '<em><b>Body Texture</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Body Texture</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Body Texture</em>' attribute.
   * @see #setBodyTexture(String)
   * @see ck2xtext.gfx.ck2gfx.Ck2gfxPackage#getArrowType_BodyTexture()
   * @model
   * @generated
   */
  String getBodyTexture();

  /**
   * Sets the value of the '{@link ck2xtext.gfx.ck2gfx.ArrowType#getBodyTexture <em>Body Texture</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Body Texture</em>' attribute.
   * @see #getBodyTexture()
   * @generated
   */
  void setBodyTexture(String value);

  /**
   * Returns the value of the '<em><b>Color</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Color</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Color</em>' containment reference.
   * @see #setColor(ColorRatio)
   * @see ck2xtext.gfx.ck2gfx.Ck2gfxPackage#getArrowType_Color()
   * @model containment="true"
   * @generated
   */
  ColorRatio getColor();

  /**
   * Sets the value of the '{@link ck2xtext.gfx.ck2gfx.ArrowType#getColor <em>Color</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Color</em>' containment reference.
   * @see #getColor()
   * @generated
   */
  void setColor(ColorRatio value);

  /**
   * Returns the value of the '<em><b>Color2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Color2</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Color2</em>' containment reference.
   * @see #setColor2(ColorRatio)
   * @see ck2xtext.gfx.ck2gfx.Ck2gfxPackage#getArrowType_Color2()
   * @model containment="true"
   * @generated
   */
  ColorRatio getColor2();

  /**
   * Sets the value of the '{@link ck2xtext.gfx.ck2gfx.ArrowType#getColor2 <em>Color2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Color2</em>' containment reference.
   * @see #getColor2()
   * @generated
   */
  void setColor2(ColorRatio value);

  /**
   * Returns the value of the '<em><b>End At</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>End At</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>End At</em>' attribute.
   * @see #setEndAt(double)
   * @see ck2xtext.gfx.ck2gfx.Ck2gfxPackage#getArrowType_EndAt()
   * @model
   * @generated
   */
  double getEndAt();

  /**
   * Sets the value of the '{@link ck2xtext.gfx.ck2gfx.ArrowType#getEndAt <em>End At</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>End At</em>' attribute.
   * @see #getEndAt()
   * @generated
   */
  void setEndAt(double value);

  /**
   * Returns the value of the '<em><b>Height</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Height</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Height</em>' attribute.
   * @see #setHeight(double)
   * @see ck2xtext.gfx.ck2gfx.Ck2gfxPackage#getArrowType_Height()
   * @model
   * @generated
   */
  double getHeight();

  /**
   * Sets the value of the '{@link ck2xtext.gfx.ck2gfx.ArrowType#getHeight <em>Height</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Height</em>' attribute.
   * @see #getHeight()
   * @generated
   */
  void setHeight(double value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see #setType(int)
   * @see ck2xtext.gfx.ck2gfx.Ck2gfxPackage#getArrowType_Type()
   * @model
   * @generated
   */
  int getType();

  /**
   * Sets the value of the '{@link ck2xtext.gfx.ck2gfx.ArrowType#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see #getType()
   * @generated
   */
  void setType(int value);

  /**
   * Returns the value of the '<em><b>Heading</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Heading</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Heading</em>' attribute.
   * @see #setHeading(double)
   * @see ck2xtext.gfx.ck2gfx.Ck2gfxPackage#getArrowType_Heading()
   * @model
   * @generated
   */
  double getHeading();

  /**
   * Sets the value of the '{@link ck2xtext.gfx.ck2gfx.ArrowType#getHeading <em>Heading</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Heading</em>' attribute.
   * @see #getHeading()
   * @generated
   */
  void setHeading(double value);

  /**
   * Returns the value of the '<em><b>Effect</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Effect</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Effect</em>' attribute.
   * @see #setEffect(String)
   * @see ck2xtext.gfx.ck2gfx.Ck2gfxPackage#getArrowType_Effect()
   * @model
   * @generated
   */
  String getEffect();

  /**
   * Sets the value of the '{@link ck2xtext.gfx.ck2gfx.ArrowType#getEffect <em>Effect</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Effect</em>' attribute.
   * @see #getEffect()
   * @generated
   */
  void setEffect(String value);

} // ArrowType
