/**
 * generated by Xtext 2.17.1
 */
package ck2xtext.gfx.ck2gfx;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Bitmap Fonts</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ck2xtext.gfx.ck2gfx.BitmapFonts#getTypes <em>Types</em>}</li>
 * </ul>
 *
 * @see ck2xtext.gfx.ck2gfx.Ck2gfxPackage#getBitmapFonts()
 * @model
 * @generated
 */
public interface BitmapFonts extends EObject
{
  /**
   * Returns the value of the '<em><b>Types</b></em>' containment reference list.
   * The list contents are of type {@link ck2xtext.gfx.ck2gfx.BitmapFont}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Types</em>' containment reference list.
   * @see ck2xtext.gfx.ck2gfx.Ck2gfxPackage#getBitmapFonts_Types()
   * @model containment="true"
   * @generated
   */
  EList<BitmapFont> getTypes();

} // BitmapFonts
