/**
 * generated by Xtext 2.17.1
 */
package ck2xtext.gfx.ck2gfx;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Color Ratio</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ck2xtext.gfx.ck2gfx.ColorRatio#getR <em>R</em>}</li>
 *   <li>{@link ck2xtext.gfx.ck2gfx.ColorRatio#getG <em>G</em>}</li>
 *   <li>{@link ck2xtext.gfx.ck2gfx.ColorRatio#getB <em>B</em>}</li>
 * </ul>
 *
 * @see ck2xtext.gfx.ck2gfx.Ck2gfxPackage#getColorRatio()
 * @model
 * @generated
 */
public interface ColorRatio extends EObject
{
  /**
   * Returns the value of the '<em><b>R</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>R</em>' attribute.
   * @see #setR(double)
   * @see ck2xtext.gfx.ck2gfx.Ck2gfxPackage#getColorRatio_R()
   * @model
   * @generated
   */
  double getR();

  /**
   * Sets the value of the '{@link ck2xtext.gfx.ck2gfx.ColorRatio#getR <em>R</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>R</em>' attribute.
   * @see #getR()
   * @generated
   */
  void setR(double value);

  /**
   * Returns the value of the '<em><b>G</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>G</em>' attribute.
   * @see #setG(double)
   * @see ck2xtext.gfx.ck2gfx.Ck2gfxPackage#getColorRatio_G()
   * @model
   * @generated
   */
  double getG();

  /**
   * Sets the value of the '{@link ck2xtext.gfx.ck2gfx.ColorRatio#getG <em>G</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>G</em>' attribute.
   * @see #getG()
   * @generated
   */
  void setG(double value);

  /**
   * Returns the value of the '<em><b>B</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>B</em>' attribute.
   * @see #setB(double)
   * @see ck2xtext.gfx.ck2gfx.Ck2gfxPackage#getColorRatio_B()
   * @model
   * @generated
   */
  double getB();

  /**
   * Sets the value of the '{@link ck2xtext.gfx.ck2gfx.ColorRatio#getB <em>B</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>B</em>' attribute.
   * @see #getB()
   * @generated
   */
  void setB(double value);

} // ColorRatio
