/**
 * generated by Xtext 2.17.1
 */
package ck2xtext.gfx.ck2gfx;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Pdxmesh</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ck2xtext.gfx.ck2gfx.Pdxmesh#getName <em>Name</em>}</li>
 *   <li>{@link ck2xtext.gfx.ck2gfx.Pdxmesh#getActorFile <em>Actor File</em>}</li>
 *   <li>{@link ck2xtext.gfx.ck2gfx.Pdxmesh#getScale <em>Scale</em>}</li>
 *   <li>{@link ck2xtext.gfx.ck2gfx.Pdxmesh#getCullDistance <em>Cull Distance</em>}</li>
 *   <li>{@link ck2xtext.gfx.ck2gfx.Pdxmesh#isScaleOnCullDistance <em>Scale On Cull Distance</em>}</li>
 * </ul>
 *
 * @see ck2xtext.gfx.ck2gfx.Ck2gfxPackage#getPdxmesh()
 * @model
 * @generated
 */
public interface Pdxmesh extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see ck2xtext.gfx.ck2gfx.Ck2gfxPackage#getPdxmesh_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link ck2xtext.gfx.ck2gfx.Pdxmesh#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Actor File</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Actor File</em>' attribute.
   * @see #setActorFile(String)
   * @see ck2xtext.gfx.ck2gfx.Ck2gfxPackage#getPdxmesh_ActorFile()
   * @model
   * @generated
   */
  String getActorFile();

  /**
   * Sets the value of the '{@link ck2xtext.gfx.ck2gfx.Pdxmesh#getActorFile <em>Actor File</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Actor File</em>' attribute.
   * @see #getActorFile()
   * @generated
   */
  void setActorFile(String value);

  /**
   * Returns the value of the '<em><b>Scale</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Scale</em>' attribute.
   * @see #setScale(double)
   * @see ck2xtext.gfx.ck2gfx.Ck2gfxPackage#getPdxmesh_Scale()
   * @model
   * @generated
   */
  double getScale();

  /**
   * Sets the value of the '{@link ck2xtext.gfx.ck2gfx.Pdxmesh#getScale <em>Scale</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Scale</em>' attribute.
   * @see #getScale()
   * @generated
   */
  void setScale(double value);

  /**
   * Returns the value of the '<em><b>Cull Distance</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cull Distance</em>' attribute.
   * @see #setCullDistance(double)
   * @see ck2xtext.gfx.ck2gfx.Ck2gfxPackage#getPdxmesh_CullDistance()
   * @model
   * @generated
   */
  double getCullDistance();

  /**
   * Sets the value of the '{@link ck2xtext.gfx.ck2gfx.Pdxmesh#getCullDistance <em>Cull Distance</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cull Distance</em>' attribute.
   * @see #getCullDistance()
   * @generated
   */
  void setCullDistance(double value);

  /**
   * Returns the value of the '<em><b>Scale On Cull Distance</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Scale On Cull Distance</em>' attribute.
   * @see #setScaleOnCullDistance(boolean)
   * @see ck2xtext.gfx.ck2gfx.Ck2gfxPackage#getPdxmesh_ScaleOnCullDistance()
   * @model
   * @generated
   */
  boolean isScaleOnCullDistance();

  /**
   * Sets the value of the '{@link ck2xtext.gfx.ck2gfx.Pdxmesh#isScaleOnCullDistance <em>Scale On Cull Distance</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Scale On Cull Distance</em>' attribute.
   * @see #isScaleOnCullDistance()
   * @generated
   */
  void setScaleOnCullDistance(boolean value);

} // Pdxmesh
