/*
 * generated by Xtext 2.14.0
 */
package ck2xtext.common;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class Ck2TerminalsRuntimeModule extends AbstractCk2TerminalsRuntimeModule {
}
