/*
 * generated by Xtext 2.14.0
 */
package ck2xtext.gfx.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
public class Ck2GfxProposalProvider extends AbstractCk2GfxProposalProvider {
}
