language: java
jdk: oraclejdk8
script: mvn verify
after_failure: 
 - cat $TRAVIS_BUILD_DIR/ck2xtext.tests/target/work/data/.metadata/.log
 - cat $TRAVIS_BUILD_DIR/ck2xtext.ui.tests/target/work/data/.metadata/.log