language: java
jdk: oraclejdk8
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script: mvn verify
after_failure: 
 - cat $TRAVIS_BUILD_DIR/ck2xtext.tests/target/work/data/.metadata/.log
 - cat $TRAVIS_BUILD_DIR/ck2xtext.ui.tests/target/work/data/.metadata/.log