/*
 * generated by Xtext 2.9.1
 */
package ck2xtext.generic.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.IXtextEditorCallback;

import ck2xtext.generic.ui.AbstractCk2UiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class Ck2UiModule extends AbstractCk2UiModule {

	public Ck2UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	/**
	 * Disable Xtext nature popup
	 */
	@Override
	public Class<? extends IXtextEditorCallback> bindIXtextEditorCallback() {
		return IXtextEditorCallback.NullImpl.class;
	}
}
