/*
 * generated by Xtext 2.9.1
 */
package ck2xtext;

import org.eclipse.xtext.conversion.IValueConverterService;

import ck2xtext.conversion.Ck2ValueConverterService;

/**
 * Use this class to register components to be used at runtime / without the
 * Equinox extension registry.
 */
public class Ck2RuntimeModule extends AbstractCk2RuntimeModule {

	@Override
	public Class<? extends IValueConverterService> bindIValueConverterService() {
		// return DefaultTerminalConverters.class;
		return Ck2ValueConverterService.class;

	}
}
