/*
 * generated by Xtext 2.17.1
 */
package ck2xtext.common.ui;

import com.google.inject.Provider;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.resource.containers.IAllContainersState;
import org.eclipse.xtext.ui.DefaultUiModule;
import org.eclipse.xtext.ui.shared.Access;

/**
 * Manual modifications go to {@link Ck2TerminalsUiModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractCk2TerminalsUiModule extends DefaultUiModule {

	public AbstractCk2TerminalsUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	// contributed by org.eclipse.xtext.xtext.generator.ImplicitFragment
	public Provider<? extends IAllContainersState> provideIAllContainersState() {
		return Access.getJavaProjectsState();
	}
	
}
