/*
 * generated by Xtext 2.9.1
 */
package ck2xtext.generic.ui.contentassist;

import ck2xtext.generic.ui.contentassist.AbstractCk2ProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
public class Ck2ProposalProvider extends AbstractCk2ProposalProvider {
}
