/**
 * generated by Xtext 2.15.0
 */
package ck2xtext.generic.ck2;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see ck2xtext.generic.ck2.Ck2Package
 * @generated
 */
public interface Ck2Factory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  Ck2Factory eINSTANCE = ck2xtext.generic.ck2.impl.Ck2FactoryImpl.init();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns a new object of class '<em>List</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>List</em>'.
   * @generated
   */
  List createList();

  /**
   * Returns a new object of class '<em>Property</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Property</em>'.
   * @generated
   */
  Property createProperty();

  /**
   * Returns a new object of class '<em>Clause</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Clause</em>'.
   * @generated
   */
  Clause createClause();

  /**
   * Returns a new object of class '<em>String Property</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>String Property</em>'.
   * @generated
   */
  StringProperty createStringProperty();

  /**
   * Returns a new object of class '<em>Id Property</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Id Property</em>'.
   * @generated
   */
  IdProperty createIdProperty();

  /**
   * Returns a new object of class '<em>Command Property</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Command Property</em>'.
   * @generated
   */
  CommandProperty createCommandProperty();

  /**
   * Returns a new object of class '<em>Bool Property</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Bool Property</em>'.
   * @generated
   */
  BoolProperty createBoolProperty();

  /**
   * Returns a new object of class '<em>Date Property</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Date Property</em>'.
   * @generated
   */
  DateProperty createDateProperty();

  /**
   * Returns a new object of class '<em>Integer Property</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Integer Property</em>'.
   * @generated
   */
  IntegerProperty createIntegerProperty();

  /**
   * Returns a new object of class '<em>Double Property</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Double Property</em>'.
   * @generated
   */
  DoubleProperty createDoubleProperty();

  /**
   * Returns a new object of class '<em>Hexadecimal Property</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Hexadecimal Property</em>'.
   * @generated
   */
  HexadecimalProperty createHexadecimalProperty();

  /**
   * Returns a new object of class '<em>List Property</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>List Property</em>'.
   * @generated
   */
  ListProperty createListProperty();

  /**
   * Returns a new object of class '<em>Id Clause Property</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Id Clause Property</em>'.
   * @generated
   */
  IdClauseProperty createIdClauseProperty();

  /**
   * Returns a new object of class '<em>Int Clause Property</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Int Clause Property</em>'.
   * @generated
   */
  IntClauseProperty createIntClauseProperty();

  /**
   * Returns a new object of class '<em>Date Clause Property</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Date Clause Property</em>'.
   * @generated
   */
  DateClauseProperty createDateClauseProperty();

  /**
   * Returns a new object of class '<em>Probability Property</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Probability Property</em>'.
   * @generated
   */
  ProbabilityProperty createProbabilityProperty();

  /**
   * Returns a new object of class '<em>Bool Clause Property</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Bool Clause Property</em>'.
   * @generated
   */
  BoolClauseProperty createBoolClauseProperty();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  Ck2Package getCk2Package();

} //Ck2Factory
