/**
 * generated by Xtext 2.15.0
 */
package ck2xtext.generic.ck2;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Property</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ck2xtext.generic.ck2.Ck2Package#getProperty()
 * @model
 * @generated
 */
public interface Property extends EObject
{
} // Property
