/*
 * generated by Xtext 2.14.0
 */
package ck2xtext.gfx;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class Ck2GfxStandaloneSetup extends Ck2GfxStandaloneSetupGenerated {

	public static void doSetup() {
		new Ck2GfxStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
