/*
 * generated by Xtext 2.17.1
 */
package ck2xtext.gfx.ui.tests;

import ck2xtext.ui.internal.Ck2xtextActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class Ck2GfxUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Ck2xtextActivator.getInstance().getInjector("ck2xtext.gfx.Ck2Gfx");
	}

}
